### ISSUE TITLE
Please say Hello to Adam!

### ISSUE THREAD

**Issue by stefanwille** [stefanwille/railsgirls#31]
Next week I will be in Vienna for a seminar, but the project group meet nevertheless. My colleague Adam will work with you that night.

Thanks Adam!

Please say hello to Adam :smile:

**Comment by Powerglove** [comment]
Cool, thank you, Adam!

**Comment by Paulina84** [comment]
hello Adam! thank you! :)

2015-09-23 11:41 GMT+02:00 Johanna Lang <notifications@github.com>:

**Comment by supernoir** [comment]
Hi Adam! Thanks!

**Comment by Paulina84** [comment]
hi!

my children's kita is closed for Thursday and Friday and therefore we are
off on Wednesday evening and I cannot come for our meetup :(((.
I hope to see you next week!

And... big news!!! I got an IT job (testing)!!! I am so happy!!!

have a good day!!!

Paulina



2015-09-27 15:59 GMT+02:00 Conny <notifications@github.com>:

**Comment by stefanwille** [comment]
@Paulina84 Great! My congratulations!! :smiley:

**Comment by supernoir** [comment]
@paulina84 cool, so happy for you!!

**Comment by Paulina84** [comment]
Thank you Conny and Stefan! I am so happy!

Wysłane z iPhone'a

Dnia 29 wrz 2015 o godz. 21:41 Conny <notifications@github.com> napisał(a):

**Comment by 019a** [comment]
Awesome news! You did it! Congratulations, Paulina!

**Comment by mjbln** [comment]
Great! :) Congratulations!!!!!

**Comment by Paulina84** [comment]
thank you guys! yes, I did it! I am starting on 19th :)))

2015-09-29 23:00 GMT+02:00 mjbln <notifications@github.com>:

**Comment by supernoir** [comment]
Hello everyone! There's a good chance I won't make it tonight, however if you guys want to continue working on our app project, I am available via e-mail or phone for questions and decisions. Have a good time!

**Comment by mjbln** [comment]
I cannot go tomorrow, sorry :/

**Comment by stefanwille** [comment]
You will be missed!

Von meinem iPhone gesendet

> Am 07.10.2015 um 00:41 schrieb mjbln <notifications@github.com>:
> 
> I cannot go tomorrow, sorry :/

**Comment by AnneNo** [comment]
Where do we meet today? 7pm?!

**Comment by stefanwille** [comment]
Today we meet at 7pm at Nokia HERE, Invalidenstr 116, at the reception desk.

**Comment by AnneNo** [comment]
Thanks, see you there!

**Comment by mjbln** [comment]
Hallo :)

Leider muss ich 10 Wochen weg sein. Ich habe ein Kurs beim Arbeit und so 
lange es dauert, kann ich nicht vorbei kommen :/ Schade!

Danach komme ich gerne zurück, es macht viel Spass mit euch zu lernen :)

LG,
mj

**Comment by stefanwille** [comment]
Liebe Maria,

sehr schade! Ich freue mich drauf, dass Du wieder kommst :)
