### ISSUE TITLE
Next Wednesday (9.12.2015): Christmas Party at Kulturbrauerei (NOT at Nokia HERE!)

### ISSUE THREAD

**Issue by stefanwille** [stefanwille/railsgirls#36]
Hello,

next Wednesday we meet 

  **at 7pm at the hotdog vendor at the corner of Danziger Straße and Schönhauser Allee (next to Manolo's Cafe)**

and then we will head towards the christmas market in Kulturbrauerei.

Please join us!

![Christmas Market](http://www.schwaebischhall.de/typo3temp/pics/f6a37ebd54.jpg)

**Comment by supernoir** [comment]
Awesome :) Great idea.

**Comment by stefanwille** [comment]
Anne, please confirm that you saw this!

**Comment by AnneNo** [comment]
Sorry, I saw the first message but not the last one. I'm in ;-) Looking
forward to Glühwein ...


2015-12-03 10:27 GMT+01:00 Stefan Wille <notifications@github.com>:

**Comment by mjbln** [comment]
El 03/12/15 a las 00:07, Conny escribió:
> Awesome :) Great idea.
>
> On Wed, Dec 2, 2015, 10:18 PM Stefan Wille <notifications@github.com> 
> wrote:
>
> > Hello,
> >
> > next Wednesday we meet at 7pm at the hotdog vendor at the corner of
> > Eberswalder Straße and Danziger (next to Manolo's Cafe) and then we will
> > head towards the christmas market in Kulturbrauerei.
> >
> > Please join us!
> >
> > [image: Christmas Market]
> > 
> <https://camo.githubusercontent.com/1589b54c9dab235077aea0c552e53687d9d8ee73/687474703a2f2f7777772e736368776165626973636868616c6c2e64652f7479706f3374656d702f706963732f663661333765626435342e6a7067>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/stefanwille/railsgirls/issues/36>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/stefanwille/railsgirls/issues/36#issuecomment-161462350>.
>
I will be there too :) i am coming back in January ;)

**Comment by stefanwille** [comment]
Great! :santa:

**Comment by stefanwille** [comment]
The Hot Dog place where we meet is called Mister Miller Hot Dog, in Danziger Straße 2.

![Mister Miller](http://newyamya.indyco.net/admin/uploaded_image/93.jpg)

**Comment by stefanwille** [comment]
It was a fun night :-)
