### ISSUE TITLE
Christmas Break: 20.12.2015 - 31.12.2015

### ISSUE THREAD

**Issue by stefanwille** [stefanwille/railsgirls#37]
The project group will be on christmas break from 20.12.2015 - 31.12.2015. After today's meeting we will meet again on 6.1.2016!

**Comment by 019a** [comment]
Stefan, I'm running late today but I'll be there in 5 min. Can someone pick
me up?

**Comment by supernoir** [comment]
# Nooooooooooooooooo!!!!
![nooooooo_luke_skywalker](https://cloud.githubusercontent.com/assets/13038195/11849364/c8918bb2-a427-11e5-8515-0e7f71b32825.gif)

## Have a great Xmas everyone, and of course - a Happy New Year!!!
![giphy](https://cloud.githubusercontent.com/assets/13038195/11849727/96fcb674-a429-11e5-8909-c2d575b1ed34.gif)

### And if you want to meet between  Dec 18 and Dec 28 (except for Dec 24/25) drop me a line - e-mail, slack, whatsapp...!

**Comment by stefanwille** [comment]
Next meeting is today, at HERE (as before). See you then! :smile:

**Comment by 019a** [comment]
Oi, oops! I thought it would be next week and made plans. :( Have fun and
see you then! Olga
